FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY generate_employees.py .

EXPOSE 8443

CMD ["python", "server.py"]
